# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
