# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 22:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20160724_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='number_of_participants',
        ),
        migrations.AddField(
            model_name='organisation',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Environment', 'Environment'), ('Public Services', 'Public Services')], default='Education', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='email_organisation',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='organisation',
            name='locations',
            field=models.CharField(default='London', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone_number',
            field=models.CharField(blank=True, default='000000000', max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.CharField(default='www.website.com', max_length=255),
        ),
    ]
