# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 22:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_auto_20160728_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='cover_picture',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='organisation/cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='front_picture',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='organisation/profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Environment', 'Environment'), ('Public Services', 'Public Services')], max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email_organisation',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='locations',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(max_length=255),
        ),
    ]
