# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 23:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_auto_20160728_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='cover_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='organisation/cover'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='front_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='organisation/profile'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
