# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='t',
        ),
    ]
