# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160716_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, default='/default/no-img.jpg', upload_to='users/'),
        ),
    ]
