# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 23:39
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20160716_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='users/'),
        ),
    ]
