# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20160729_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_picture',
            new_name='front_picture',
        ),
    ]
