# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
