# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developer', '0002_auto_20160724_1219'),
        ('partnership', '0002_auto_20160722_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField(choices=[(0, 'user'), (1, 'organisation')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([('user', 'organisation')]),
        ),
    ]
