# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0002_pendingrequest_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
