# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-15 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='organisation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
