# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0003_auto_20161018_1649'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set([('user', 'organisation')]),
        ),
    ]
