# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20161206_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.TextField(default='def'),
        ),
    ]
